import { pgTable, text, integer, boolean, jsonb, real, uuid, timestamp } from "drizzle-orm/pg-core";

// --- STRICT TYPES FOR JSON COLUMNS ---

// AI Types (The CTO Brain)
export interface AIBlueprint {
  tagline: string;
  description: string;
  techStack: any[]; 
  databaseSchema: any[];
  roadmap: any[];
  brutalTruth: string; 
}

// Resource Helper Type
export interface ResourceItem {
  id: string;
  type: "link" | "note" | "todo";
  content: string;
  url?: string;
  isCompleted?: boolean;
  createdAt: number;
}

// Fitness Types (Keep these so other pages don't break)
export interface Set { id: string; weight: number; reps: number; completed: boolean; }
export interface Exercise { id: string; name: string; sets: Set[]; isCollapsed: boolean; }
export interface WorkoutSession { id: string; name: string; startTime: number; endTime: number | null; exercises: Exercise[]; }
export interface FoodItem { id: string; name: string; cals: number; p: number; c: number; f: number; }

// 1. USER TABLE
export const users = pgTable("users", {
  id: uuid("id").primaryKey().defaultRandom(),
  clerkId: text("clerk_id").unique().notNull(),
  email: text("email").notNull(),
  name: text("name"),
  imageUrl: text("image_url"),
  createdAt: timestamp("created_at").defaultNow(),
});

// 2. FITNESS DAYS
export const fitnessDays = pgTable("fitness_days", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(), 
  date: text("date").notNull(),
  isRestDay: boolean("is_rest_day").default(false).notNull(),
  waterGoal: integer("water_goal").default(3000).notNull(),
  waterIntake: integer("water_intake").default(0).notNull(),
  stepGoal: integer("step_goal").default(10000).notNull(),
  stepCount: integer("step_count").default(0).notNull(),
  bodyWeight: real("body_weight"),
  targetWeight: real("target_weight").default(75),
  sessions: jsonb("sessions").$type<WorkoutSession[]>().default([]).notNull(),
  meals: jsonb("meals").$type<FoodItem[]>().default([]).notNull(),
  macroGoal: jsonb("macro_goal").$type<{ cals: number; p: number; c: number; f: number }>().default({ cals: 2500, p: 180, c: 250, f: 70 }).notNull(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// 3. PROJECTS TABLE (Updated for AI CTO)
export const projects = pgTable("projects", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  name: text("name").notNull(),
  vision: text("vision"),
  status: text("status").default("building"), // building, shipped, dropped
  techStack: jsonb("tech_stack").$type<string[]>().default([]).notNull(),
  complexityScore: integer("complexity_score").default(1),
  revenuePotential: integer("revenue_potential").default(0),
  
  // The Blueprint generated by AI
  aiBlueprint: jsonb("ai_blueprint").$type<AIBlueprint>(), 
  
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// 4. PROJECT RESOURCES (The Neural Link - Notes inside projects)
export const projectResources = pgTable("project_resources", {
  id: uuid("id").primaryKey().defaultRandom(),
  projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
  userId: text("user_id").notNull(),
  type: text("type").notNull(), // 'link', 'note', 'todo'
  title: text("title").notNull(),
  content: text("content"), // For notes or link descriptions
  url: text("url"), // For links
  isCompleted: boolean("is_completed").default(false), // For todos
  createdAt: timestamp("created_at").defaultNow(),
});

// 5. IDEA VAULT
export const ideas = pgTable("ideas", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  title: text("title").notNull(),
  problem: text("problem").notNull(),
  isValidated: boolean("is_validated").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// 6. DAILY DEV LOGS
export const devLogs = pgTable("dev_logs", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  projectId: uuid("project_id").references(() => projects.id),
  date: text("date").notNull(), // YYYY-MM-DD
  tasksCompleted: jsonb("tasks_completed").$type<string[]>().default([]).notNull(),
  blockers: text("blockers"),
  energyLevel: integer("energy_level"), // 1-10
  commitCount: integer("commit_count").default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

// 7. TASKS (V3 - Kept as is)
export const tasks = pgTable("tasks", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  title: text("title").notNull(),
  
  // Basic Details
  description: text("description"), // Notes
  category: text("category").default("work"), // work, personal, health, learning
  priority: text("priority").default("medium"), // low, medium, high, urgent
  
  // Status & Progress Tracking
  status: text("status").default("pending"), // pending, in-progress, completed, skipped
  progress: integer("progress").default(0), // 0 to 100%

  // Scheduling Logic
  taskType: text("task_type").default("flexible"), // 'fixed' or 'flexible'
  startTime: text("start_time"), // Nullable (only for fixed tasks)
  duration: integer("duration").default(30), // minutes

  energy: text("energy").default("medium"), // low, medium, high
  date: text("date").notNull(), // YYYY-MM-DD
  skippedReason: text("skipped_reason"),
  
  // Keeping order for drag-and-drop safety
  order: integer("order").default(0),
  
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// 8. SPORTS MATCHES (THE ARENA - V8 PURE SCHEDULE)
export const sportsMatches = pgTable("sports_matches", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(),
  
  // Event Info
  sport: text("sport").notNull(), // 'football', 'cricket', 'f1'
  title: text("title").notNull(), // "India vs Pakistan"
  tournament: text("tournament"), // "World Cup"
  platform: text("platform"), // "Hotstar"
  
  // Logistics
  date: text("date").notNull(), // YYYY-MM-DD
  time: text("time").notNull(), // HH:MM
  duration: integer("duration").default(180), // Minutes (Important for conflict calc)
  
  // AI Prep
  aiIntel: text("ai_intel"), // "Key Battle: Kohli vs Shaheen"
  
  createdAt: timestamp("created_at").defaultNow(),
});